### ISSUE TITLE
Crash with QGIS 3.22

### ISSUE THREAD

**Issue by romefi** [opengisch/shlocator#2]
Mit QGIS 3.22 gibt es hin und wieder einen Absturz, wenn über Shlocator ein Suchresultat angezeigt werden soll. Es ist nicht nachvollziehbar wieso. Es ist nicht immer beim gleichen Suchresultat und tritt auch mal mehr mal weniger auf. Auch wird keine sinnvolle Fehlermeldung im Crashreport angezeigt.

Am besten einfach ein paar Suchresultate auswählen, bis der Fehler mal auftritt.

![qis_3_22_crashes_with_sh_locator](https://user-images.githubusercontent.com/26796989/152493076-923c5fd9-3b12-444a-9e8e-3d1e2038aeea.gif)

@m-kuhn ich weiss nicht genau, wer jetzt bei euch zuständig ist, du kannst das Issue gerne weiterleiten. Wäre froh, wenn das bald gelöst werden könnte, da wir QGIS 3.22 erst ausrollen können, wenn das behoben ist. Du kannst den Aufwand von unserem Support abziehen. Wenn der Aufwand grösser als 1 Tag ist, bitte im Meldung.

Vielen Dank.

**Comment by m-kuhn** [comment]
Danke fürs Melden und das gute Video.

Das ist aufgenommen und sollte voraussichtlich gut lösbar sein, analoge Probleme mussten in der Vergangenheit (seit 3.18) bereits in anderen Suchplugins gelöst werden.

**Comment by romefi** [comment]
@ZsanettMed, da Matthias noch in den Ferien ist... Könntest du abklären, was der Aufwand für die Behebung dieses Bugs ist und wann es umgesetzt werden kann? Wenn du nicht zuständig bist, kannst du das gerne weitergeben :)

Wir planen Ende April das go-live von QGIS 3.22 und wären froh, wenn der ShLocator bis dann auf QGIS 3.22 läuft. Vielen Dank.
